server:
  port:

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(1JjULlW7yPo9u4OAYFz0TX958u4lkAGRjyOgA8J28Zx7J/DZAY6FbUpLAXZyKuudz1aKUvbLHc5HLl1w7tXqzw==)
    username: ENC(97LEGF/Ob7Wzj4dp3sTLSQ==)
    password: ENC(pLvcM6HCCj5eO7BxxZZKrRFMRKyBazVc)
  redis:
    host: ENC(g7NZ4El+KHpgYCk/Io35YGIbnL7z+2Ni)

riot:
  access-key: RGAPI-a7a64eaf-b987-43b2-a7b7-2fd73149eb8f

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none